### ISSUE TITLE
 Cannot read property 'connected' of undefined [WINDOWS]

### ISSUE THREAD

**Issue by heldrida** [gruntjs/grunt-contrib-jasmine#156]
I've got the error on a Windows Machine, I'm using Git Bash:

	$ grunt
	Running "jasmine:src" (jasmine) task
	Testing jasmine specs via PhantomJS

	Warning: Cannot read property 'connected' of undefined Use --force to continue.

	Aborted due to warnings.

After the initial setup, running the commands:

	npm install grunt
	npm install grunt-contrib-jasmine --save-dev

And using the following Gruntfile.js:

	'use strict';

	module.exports = function (grunt) {

	    grunt.initConfig({
	        jasmine: {
	            src: 'app/**/*.js',
	            specs: 'specs/**/*.js'
	        }
	    });

	    grunt.loadNpmTasks('grunt-contrib-jasmine');

	    grunt.registerTask('default', 'jasmine');

	};

Thanks for looking!

**Comment by jsilland** [comment]
Is there a known workaround for this issue? This is happening on my Mac - this isn't an issue proper to the Windows platform.

It seems established that the fault is with `grunt-lib-phantomjs` - I'm wondering if there's a way to avoid that code path to be executed? Phrased differently: how come this isn't a problem for all users of this plugin?

My configuration is rather trivial – any help appreciated

```coffee
grunt.initConfig
    jasmine:
      src: 'lib/assets/javascripts/strava_formatters/en-US.js'
      options:
        specs: 'build/**/*Spec.js'
        vendor: 'node_modules/twitter_cldr/min/en.min.js'
```

**Comment by jazzhammer** [comment]
i have the same problem, running on a mac: yosemite 10.10.2.

at this line, phantomHSHandle is the undefined thing that phantomjs.js is complaining about:

Warning: Cannot read property 'connected' of undefined Use --force to continue.
TypeError: Cannot read property 'connected' of undefined
    at kill (c:\Users\foo\MyProjects\testingJasmine\node_modules\grunt-contrib-jasmine\node_modules\grunt-lib-phantomjs\lib\phantomjs.js:59:28)

phantomJSHandle is coming back from a call to grunt.util.spawn( args, callback(err, result, code)).

the code is 127 so phantom really is having an issue spawning the phantomjs command.
why would it have an issue with this ? probably because in this call to .spawn: 
    ...
    return phantomJSHandle = grunt.util.spawn(
      {
        cmd: binPath,
    ...
 
binPath is null !!!!

the grunt.util.spawn documentation says: 

grunt.util.spawn(options, doneFunction)
     The options object has these possible properties:
          var options = {
               // The command to execute. It should be in the system path.
               cmd: commandToExecute,

so... 

i hardcoded the path to one of the phantomjs executables i've installed as a result of trying to figure this out:   '/Applications/phantomjs/bin/phantomjs'

my grunt then hangs on 

    Running "jasmine:pivotal" (jasmine) task
    Testing jasmine specs via PhantomJS

when i set binPath to my user's local phantomjs: 

    /usr/local/lib/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs

my jasmine tests run.  great.  so... 

this is clearly a path problem here:

    // Get path to phantomjs binary
      var binPath = require('phantomjs').path;

i'm going to leave this hack in my phantom.js file because i have a deadline to meet real soon and i need to get some work done. i'll get back to this next month maybe. or... 

maybe somebody else can figure out why require doesn't know where my phantomjs executable is.

**Comment by crlf0710** [comment]
i found that somehow phantomjs dependency is not properly installed.

    cd node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
    npm install

make this problem disappear...

**Comment by nmccready** [comment]
This problem is a blocker and it is not windows only as @jazzhammer stated

**Comment by nmccready** [comment]
This is a problem for a version but upgrading from 0.8.2 to 0.9.2 resolved the issue for me on OSX.

**Comment by leondeng** [comment]
Met similar issue with grunt test by jasmine:
 Warning: Cannot read property 'pid' of undefined Use --force to continue.

solved by:
cd node_modules/phantomjs/
npm install

Thanks to crlf0710
