### ISSUE TITLE
Can the .grunt directory be created under node_modules instead of project root?

### ISSUE THREAD

**Issue by David-Hari** [gruntjs/grunt-contrib-jasmine#170]
It's annoying seeing yet another generated directory under my project's root. Could all the stuff in .grunt/grunt-contrib-jasmine be put in node_modules/grunt-contrib-jasmine instead? Given that this is a Node module, that seems to be the appropriate place.

**Comment by gyandeeps** [comment]
Or if we can have that as an option which can be supplied by the consumer. @vladikoff

**Comment by samkelleher** [comment]
Is the reasoning behind creating the files under the `.grunt` directory to do with source control and deployment?  Some people do not commit their `node_modules` directory to source control, and may not also include them in front-end hosting.  By putting the jasmine files in the .grunt folder, we can commit just these files - meaning our SpecRunner.html will continue to run even if the node modules haven't been installed.

**Comment by matatk** [comment]
I think it's great to have Jasmine's code locally, so the SpecRunner can be hosted (e.g. via GtiHub pages) and the tests can be run directly from there.  However, I really would like to have Jasmine's code in my `test/` directory, rather than `.grunt/` but there doesn't seem to be an option as to where to put the Jasmine code -- please could such an option be added?

**Comment by deckar01** [comment]
@vladikoff Would you be interested in reviewing a PR that implements @gyandeeps's suggestion by adding a configuration option for `tempDir` that defaults to `".grunt/grunt-contrib-jasmine"`?
