### ISSUE TITLE
jasmine.clock().install() throws error

### ISSUE THREAD

**Issue by plondon** [gruntjs/grunt-contrib-jasmine#213]
```javascript
beforeEach(function() {
  jasmine.clock().install();
});
```

throws **Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?**

```javascript
beforeEach(function() {
  jasmine.clock().uninstall();
  jasmine.clock().install();
});
```

Fixed my issue.

**Comment by NessDan** [comment]
+1 Same issue and your fix works, but this shouldn't be an issue to begin with.

**Comment by mygoodgomez** [comment]
In the Jasmine docs, they give this example:
```
beforeEach(function() {
    timerCallback = jasmine.createSpy("timerCallback");
    jasmine.clock().install();
});

afterEach(function() {
    jasmine.clock().uninstall();
});
```

I ran into the issue as well, and I guess uninstalling it is the solution.

**Comment by jakefreeberg** [comment]
:+1: Thanks @mygoodgomez

**Comment by Sjors** [comment]
I experienced the same issue - with the same fix. It happens when I run all tests in my project, but not when I use `fdescribe` to only run the tests in [one file](https://github.com/blockchain/My-Wallet-V3/blob/610b6c909fd534a0bfde04f041fc16c22bb5f3ea/tests/coinify/coinify_trade_spec.js.coffee). Perhaps some other test file uses `jasmine.clock()` (via a dependency) and doesn't clean up?

**Comment by djungowski** [comment]
Usually this happens, when you don't uninstall the clock. Instead of uninstalling and then installing the clock in the beforeEach, do this instead:
```javascript
beforeEach(function() {
  jasmine.clock().install();
});

afterEach(function() {
  jasmine.clock().uninstall();
});
```
Otherwise all following tests will automatically run with the installed clock.

**Comment by jamiehand** [comment]
@djungowski I was doing as you suggested, but still getting the error listed by OP. The fix listed by OP got rid of the error for me, but it seems strange to need to uninstall before installing, especially because the clock doesn't seem to be otherwise installed; when I try to use `jasmine.clock()` in a test without `jasmine.clock().install()` in `beforeEach()`, I get this error:

`Mock clock is not installed, use jasmine.clock().install()`

**Comment by Hmbucker** [comment]
I ran into the issue by a library which was doing something as:
`var a=window.setTimeout;

describe('installing the clock', function () {
  beforeEach(function () {
    jasmine.clock().install();
  });
  
  afterEach(function () {
    jasmine.clock().uninstall();
  });
  
  it('increases the time', function () {
    jasmine.clock().mockDate();
    
    var start = Date.now();
    var end;
    
    //window.setTimeout(function () {
    //  end = Date.now();
    //}, 100);
    a(function () {
      end = Date.now();
    }, 100);
    
    jasmine.clock().tick(100);
    
    expect(end - start).toBe(100);
  });
});`

**Comment by devBrunoLins** [comment]
> ```js
> beforeEach(function() {
>   jasmine.clock().install();
> });
> ```
> 
> throws **Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?**
> 
> ```js
> beforeEach(function() {
>   jasmine.clock().uninstall();
>   jasmine.clock().install();
> });
> ```
> 
> Fixed my issue.

This fix my issue to

**Comment by pushkin-** [comment]
@Hmbucker  Can you clarify this line: "switching the lines below the commented ones, fixes the issue."

You mean swapping `jasmine.clock().tick...` with `a(function...)` fixes it? I don't understand the issue.

**Comment by kylin-ma** [comment]
> > ```js
> > beforeEach(function() {
> >   jasmine.clock().install();
> > });
> > ```
> > 
> > 
> > throws **Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?**
> > ```js
> > beforeEach(function() {
> >   jasmine.clock().uninstall();
> >   jasmine.clock().install();
> > });
> > ```
> > 
> > 
> > Fixed my issue.
> 
> This fix my issue to
