### ISSUE TITLE
Set the base path for this plugin to calculate routes to helpers in the .grunt/ folder?

### ISSUE THREAD

**Issue by SimplGy** [gruntjs/grunt-contrib-jasmine#60]
I use live-reload to develop an application.
I would like grunt-contrib-jasmine to place its generated spec runner html file in the live-reload folder so that developers can visit it in the browser. The problem is that the pathing is all based on being in grunt root. Is there a way to change this?

here's my config:

    jasmine:
      runSpecs:
        options:
          specs: "<%= yeoman.dev %>/**/*.spec.js"
          outfile: "<%= yeoman.dev %>/_autoSpec.html"
          template: require('grunt-template-jasmine-requirejs')
          #appDir: "<%= yeoman.dev %>" #This is the option I'm looking for

Is it possible to move the location of the generated spec runner without breaking url references? I'm aware of require's base path setting, but this would impact normal application dependencies.

**Comment by moneypenny** [comment]
@geekytime it doesn't look like .grunt gets put in the same place as the generated _SpecRunner.html.

**Comment by matatk** [comment]
This issue seems quite similar to #170, in which I asked if it might be possible to choose where to put the contents of the current `.grunt/` directory (I've got the SpecRunner in `test/`, which is hosted via GitHub Pages, and it'd be great -- much neater -- to be able to put Jasmine's code in `test/` as well).
